In [1]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv('./data/202207_202207_주민등록인구및세대현황_월간.csv', encoding='cp949')
df

,행정구역,2022년07월_거주자 인구수,2022년07월_세대수,2022년07월_남자 인구수,2022년07월_여자 인구수
0,서울특별시 (1100000000),"9,386,382","4,391,372","4,550,852","4,835,530"
1,서울특별시 종로구 (1111000000),"140,389","71,377","67,928","72,461"
2,서울특별시 중구 (1114000000),"119,402","61,892","57,975","61,427"
3,서울특별시 용산구 (1117000000),"216,005","107,393","103,947","112,058"
4,서울특별시 성동구 (1120000000),"280,295","131,901","136,351","143,944"
5,서울특별시 광진구 (1121500000),"336,339","167,360","162,081","174,258"
6,서울특별시 동대문구 (1123000000),"333,759","167,405","164,366","169,393"
7,서울특별시 중랑구 (1126000000),"384,950","185,637","189,325","195,625"
8,서울특별시 성북구 (1129000000),"429,175","195,049","206,542","222,633"
9,서울특별시 강북구 (1130500000),"293,211","142,615","142,404","150,807"
10,서울특별시 도봉구 (1132000000),"311,833","137,213","151,470","160,363"
11,서울특별시 노원구 (1135000000),"503,798","215,977","242,304","261,494"
12,서울특별시 은평구 (1138000000),"468,176","212,800","223,511","244,665"
13,서울특별시 서대문구 (1141000000),"301,728","142,845","143,834","157,894"
14,서울특별시 마포구 (1144000000),"362,552","177,656","170,174","192,378"
15,서울특별시 양천구 (1147000000),"440,549","179,525","215,582","224,967"
16,서울특별시 강서구 (1150000000),"568,286","271,364","272,832","295,454"
17,서울특별시 구로구 (1153000000),"391,812","180,168","192,605","199,207"
18,서울특별시 금천구 (1154500000),"229,414","118,123","115,558","113,856"
19,서울특별시 영등포구 (1156000000),"372,472","185,884","183,265","189,207"
20,서울특별시 동작구 (1159000000),"381,787","184,793","184,548","197,239"
21,서울특별시 관악구 (1162000000),"482,450","278,386","242,365","240,085"
22,서울특별시 서초구 (1165000000),"401,084","165,461","191,633","209,451"
23,서울특별시 강남구 (1168000000),"522,874","228,621","250,063","272,811"
24,서울특별시 송파구 (1171000000),"656,576","281,987","316,247","340,329"
25,서울특별시 강동구 (1174000000),"457,466","199,940","223,942","233,524"

In [19]:
df1 = df[['행정구역', '2022년07월_거주자 인구수', '2022년07월_남자 인구수', '2022년07월_여자 인구수']]

In [20]:
df1

                       행정구역 2022년07월_거주자 인구수 2022년07월_남자 인구수 2022년07월_여자 인구수
0       서울특별시  (1100000000)        9,386,382       4,550,852       4,835,530
1    서울특별시 종로구 (1111000000)          140,389          67,928          72,461
2     서울특별시 중구 (1114000000)          119,402          57,975          61,427
3    서울특별시 용산구 (1117000000)          216,005         103,947         112,058
4    서울특별시 성동구 (1120000000)          280,295         136,351         143,944
5    서울특별시 광진구 (1121500000)          336,339         162,081         174,258
6   서울특별시 동대문구 (1123000000)          333,759         164,366         169,393
7    서울특별시 중랑구 (1126000000)          384,950         189,325         195,625
8    서울특별시 성북구 (1129000000)          429,175         206,542         222,633
9    서울특별시 강북구 (1130500000)          293,211         142,404         150,807
10   서울특별시 도봉구 (1132000000)          311,833         151,470         160,363
11   서울특별시 노원구 (1135000000)          503,798         242,304         261,494
12   서울특별시 은평구 (1138000000)          468,176         223,511         244,665
13  서울특별시 서대문구 (1141000000)          301,728         143,834         157,894
14   서울특별시 마포구 (1144000000)          362,552         170,174         192,378
15   서울특별시 양천구 (1147000000)          440,549         215,582         224,967
16   서울특별시 강서구 (1150000000)          568,286         272,832         295,454
17   서울특별시 구로구 (1153000000)          391,812         192,605         199,207
18   서울특별시 금천구 (1154500000)          229,414         115,558         113,856
19  서울특별시 영등포구 (1156000000)          372,472         183,265         189,207
20   서울특별시 동작구 (1159000000)          381,787         184,548         197,239
21   서울특별시 관악구 (1162000000)          482,450         242,365         240,085
22   서울특별시 서초구 (1165000000)          401,084         191,633         209,451
23   서울특별시 강남구 (1168000000)          522,874         250,063         272,811
24   서울특별시 송파구 (1171000000)          656,576         316,247         340,329
25   서울특별시 강동구 (1174000000)          457,466         223,942         233,524

In [21]:
df1.rename(columns = {'행정구역' : '구', '2022년07월_거주자 인구수' : '총 인구수', '2022년07월_남자 인구수' : '남자 인구수', '2022년07월_여자 인구수' : '여자 인구수'},inplace=True)

C:\Users\HYUNJIN\AppData\Local\Temp\ipykernel_7236\2191573733.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns = {'행정구역' : '구', '2022년07월_거주자 인구수' : '총 인구수', '2022년07월_남자 인구수' : '남자 인구수', '2022년07월_여자 인구수' : '여자 인구수'},inplace=True)

In [22]:
df1

                          구      총 인구수     남자 인구수     여자 인구수
0       서울특별시  (1100000000)  9,386,382  4,550,852  4,835,530
1    서울특별시 종로구 (1111000000)    140,389     67,928     72,461
2     서울특별시 중구 (1114000000)    119,402     57,975     61,427
3    서울특별시 용산구 (1117000000)    216,005    103,947    112,058
4    서울특별시 성동구 (1120000000)    280,295    136,351    143,944
5    서울특별시 광진구 (1121500000)    336,339    162,081    174,258
6   서울특별시 동대문구 (1123000000)    333,759    164,366    169,393
7    서울특별시 중랑구 (1126000000)    384,950    189,325    195,625
8    서울특별시 성북구 (1129000000)    429,175    206,542    222,633
9    서울특별시 강북구 (1130500000)    293,211    142,404    150,807
10   서울특별시 도봉구 (1132000000)    311,833    151,470    160,363
11   서울특별시 노원구 (1135000000)    503,798    242,304    261,494
12   서울특별시 은평구 (1138000000)    468,176    223,511    244,665
13  서울특별시 서대문구 (1141000000)    301,728    143,834    157,894
14   서울특별시 마포구 (1144000000)    362,552    170,174    192,378
15   서울특별시 양천구 (1147000000)    440,549    215,582    224,967
16   서울특별시 강서구 (1150000000)    568,286    272,832    295,454
17   서울특별시 구로구 (1153000000)    391,812    192,605    199,207
18   서울특별시 금천구 (1154500000)    229,414    115,558    113,856
19  서울특별시 영등포구 (1156000000)    372,472    183,265    189,207
20   서울특별시 동작구 (1159000000)    381,787    184,548    197,239
21   서울특별시 관악구 (1162000000)    482,450    242,365    240,085
22   서울특별시 서초구 (1165000000)    401,084    191,633    209,451
23   서울특별시 강남구 (1168000000)    522,874    250,063    272,811
24   서울특별시 송파구 (1171000000)    656,576    316,247    340,329
25   서울특별시 강동구 (1174000000)    457,466    223,942    233,524

In [36]:
df2 = df1.drop(0, axis=0)

In [37]:
df2

                          구    총 인구수   남자 인구수   여자 인구수
1    서울특별시 종로구 (1111000000)  140,389   67,928   72,461
2     서울특별시 중구 (1114000000)  119,402   57,975   61,427
3    서울특별시 용산구 (1117000000)  216,005  103,947  112,058
4    서울특별시 성동구 (1120000000)  280,295  136,351  143,944
5    서울특별시 광진구 (1121500000)  336,339  162,081  174,258
6   서울특별시 동대문구 (1123000000)  333,759  164,366  169,393
7    서울특별시 중랑구 (1126000000)  384,950  189,325  195,625
8    서울특별시 성북구 (1129000000)  429,175  206,542  222,633
9    서울특별시 강북구 (1130500000)  293,211  142,404  150,807
10   서울특별시 도봉구 (1132000000)  311,833  151,470  160,363
11   서울특별시 노원구 (1135000000)  503,798  242,304  261,494
12   서울특별시 은평구 (1138000000)  468,176  223,511  244,665
13  서울특별시 서대문구 (1141000000)  301,728  143,834  157,894
14   서울특별시 마포구 (1144000000)  362,552  170,174  192,378
15   서울특별시 양천구 (1147000000)  440,549  215,582  224,967
16   서울특별시 강서구 (1150000000)  568,286  272,832  295,454
17   서울특별시 구로구 (1153000000)  391,812  192,605  199,207
18   서울특별시 금천구 (1154500000)  229,414  115,558  113,856
19  서울특별시 영등포구 (1156000000)  372,472  183,265  189,207
20   서울특별시 동작구 (1159000000)  381,787  184,548  197,239
21   서울특별시 관악구 (1162000000)  482,450  242,365  240,085
22   서울특별시 서초구 (1165000000)  401,084  191,633  209,451
23   서울특별시 강남구 (1168000000)  522,874  250,063  272,811
24   서울특별시 송파구 (1171000000)  656,576  316,247  340,329
25   서울특별시 강동구 (1174000000)  457,466  223,942  233,524

In [38]:
df2['구']=df2['구'].str.replace('서울특별시 ','')

In [39]:
df2

                    구    총 인구수   남자 인구수   여자 인구수
1    종로구 (1111000000)  140,389   67,928   72,461
2     중구 (1114000000)  119,402   57,975   61,427
3    용산구 (1117000000)  216,005  103,947  112,058
4    성동구 (1120000000)  280,295  136,351  143,944
5    광진구 (1121500000)  336,339  162,081  174,258
6   동대문구 (1123000000)  333,759  164,366  169,393
7    중랑구 (1126000000)  384,950  189,325  195,625
8    성북구 (1129000000)  429,175  206,542  222,633
9    강북구 (1130500000)  293,211  142,404  150,807
10   도봉구 (1132000000)  311,833  151,470  160,363
11   노원구 (1135000000)  503,798  242,304  261,494
12   은평구 (1138000000)  468,176  223,511  244,665
13  서대문구 (1141000000)  301,728  143,834  157,894
14   마포구 (1144000000)  362,552  170,174  192,378
15   양천구 (1147000000)  440,549  215,582  224,967
16   강서구 (1150000000)  568,286  272,832  295,454
17   구로구 (1153000000)  391,812  192,605  199,207
18   금천구 (1154500000)  229,414  115,558  113,856
19  영등포구 (1156000000)  372,472  183,265  189,207
20   동작구 (1159000000)  381,787  184,548  197,239
21   관악구 (1162000000)  482,450  242,365  240,085
22   서초구 (1165000000)  401,084  191,633  209,451
23   강남구 (1168000000)  522,874  250,063  272,811
24   송파구 (1171000000)  656,576  316,247  340,329
25   강동구 (1174000000)  457,466  223,942  233,524

In [44]:
i = 0
for i in range(1, 26):
    df2.loc[i, '구']=df2.loc[i, '구'].split(' ')[0]

In [45]:
df2

       구    총 인구수   남자 인구수   여자 인구수
1    종로구  140,389   67,928   72,461
2     중구  119,402   57,975   61,427
3    용산구  216,005  103,947  112,058
4    성동구  280,295  136,351  143,944
5    광진구  336,339  162,081  174,258
6   동대문구  333,759  164,366  169,393
7    중랑구  384,950  189,325  195,625
8    성북구  429,175  206,542  222,633
9    강북구  293,211  142,404  150,807
10   도봉구  311,833  151,470  160,363
11   노원구  503,798  242,304  261,494
12   은평구  468,176  223,511  244,665
13  서대문구  301,728  143,834  157,894
14   마포구  362,552  170,174  192,378
15   양천구  440,549  215,582  224,967
16   강서구  568,286  272,832  295,454
17   구로구  391,812  192,605  199,207
18   금천구  229,414  115,558  113,856
19  영등포구  372,472  183,265  189,207
20   동작구  381,787  184,548  197,239
21   관악구  482,450  242,365  240,085
22   서초구  401,084  191,633  209,451
23   강남구  522,874  250,063  272,811
24   송파구  656,576  316,247  340,329
25   강동구  457,466  223,942  233,524

In [46]:
df2.reset_index(drop=True)

       구    총 인구수   남자 인구수   여자 인구수
0    종로구  140,389   67,928   72,461
1     중구  119,402   57,975   61,427
2    용산구  216,005  103,947  112,058
3    성동구  280,295  136,351  143,944
4    광진구  336,339  162,081  174,258
5   동대문구  333,759  164,366  169,393
6    중랑구  384,950  189,325  195,625
7    성북구  429,175  206,542  222,633
8    강북구  293,211  142,404  150,807
9    도봉구  311,833  151,470  160,363
10   노원구  503,798  242,304  261,494
11   은평구  468,176  223,511  244,665
12  서대문구  301,728  143,834  157,894
13   마포구  362,552  170,174  192,378
14   양천구  440,549  215,582  224,967
15   강서구  568,286  272,832  295,454
16   구로구  391,812  192,605  199,207
17   금천구  229,414  115,558  113,856
18  영등포구  372,472  183,265  189,207
19   동작구  381,787  184,548  197,239
20   관악구  482,450  242,365  240,085
21   서초구  401,084  191,633  209,451
22   강남구  522,874  250,063  272,811
23   송파구  656,576  316,247  340,329
24   강동구  457,466  223,942  233,524

In [47]:
df2.to_csv('./data/data_set/2022인구수.csv')