In [1]:
import pandas as pd
import numpy as np

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [34]:
GDP = pd.read_csv('./data/자치구별+지역내총생산(2015년+기준)_20220817130355.csv',
                 usecols = ['자치구별(2)', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019'])

In [35]:
GDP.head()

,자치구별(2),2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,자치구별(2),지역내총생산(당해년가격) (백만원),지역내총생산(당해년가격) (백만원),지역내총생산(당해년가격) (백만원),지역내총생산(당해년가격) (백만원),지역내총생산(당해년가격) (백만원),지역내총생산(당해년가격) (백만원),지역내총생산(당해년가격) (백만원),지역내총생산(당해년가격) (백만원),지역내총생산(당해년가격) (백만원),지역내총생산(당해년가격) (백만원)
1,소계,313281033,326415107,334324998,340711607,350258443,370167867,387364432,404079600,423742112,435927212
2,종로구,25368342,26475253,27054742,26899141,28437845,29331069,30190706,31416328,31868698,33780610
3,중구,50231606,49984232,47896948,46545834,46949514,49949249,52623501,51213292,54274488,53823217
4,용산구,9458938,9708239,9617839,9635228,9686230,10023473,10457073,11737945,12300317,12695516

In [36]:
GDP = GDP.drop(GDP.index[0])

In [37]:
GDP.rename(columns = {'자치구별(2)':'구'}, inplace = True)

In [38]:
GDP.loc[1, '구'] = '소계(백만원 단위)'

In [39]:
GDP

,구,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
1,소계(백만원 단위),313281033,326415107,334324998,340711607,350258443,370167867,387364432,404079600,423742112,435927212
2,종로구,25368342,26475253,27054742,26899141,28437845,29331069,30190706,31416328,31868698,33780610
3,중구,50231606,49984232,47896948,46545834,46949514,49949249,52623501,51213292,54274488,53823217
4,용산구,9458938,9708239,9617839,9635228,9686230,10023473,10457073,11737945,12300317,12695516
5,성동구,7594800,8134121,8714556,9158435,9597921,10231864,10662221,10735112,11657151,12167850
6,광진구,5470153,5376706,5491363,5577272,5539718,5696485,6097219,6131450,6342279,6587069
7,동대문구,5883484,6055224,6391083,6492698,6555042,6589147,7185192,7218027,7328160,7555543
8,중랑구,3558287,3589529,3809180,3912729,3918661,3856334,4120148,4283062,4452719,4741739
9,성북구,4753282,4900844,5147771,5305256,5223368,5407042,5750131,5917636,6054811,6141921
10,강북구,3523524,3099417,3034754,2794358,2762673,2759140,2952798,3057496,3207289,3283572
11,도봉구,2590667,2680341,2730446,2778965,2864374,2906723,3116564,3325320,3352742,3404872
12,노원구,4968064,5254223,5200159,5255627,5399253,5606176,5901669,6239829,6387713,6620672
13,은평구,3522078,3375379,3408442,3660969,3671864,3866400,4298312,4514825,4754342,4919715
14,서대문구,5792314,6339773,7102760,7123557,7195459,7507777,7837950,8212568,8363965,8652191
15,마포구,12104724,13633828,14832137,16128504,16959271,17955655,18926362,18740095,19474677,19943128
16,양천구,5789373,5954917,6087578,5938515,6069052,6276755,6399102,6658836,6931171,7125314
17,강서구,7553259,7992342,8110727,8923765,9097721,10149098,11420676,16772058,17607271,17458926
18,구로구,10940921,11041540,11459277,11551459,11490653,12017187,12472027,13254659,13816661,14090156
19,금천구,12415829,13589560,14513295,14541512,14234518,14953994,15751878,16385145,17162843,17614623
20,영등포구,25966200,27548300,27293987,28078087,28194672,30173741,30667943,32055158,34299880,36095497
21,동작구,5761951,5810675,5916935,5820494,5595277,5521181,5965426,6254375,6362074,6527100
22,관악구,4832579,5036256,5157841,5304105,5504127,5597548,5623923,5755018,5836563,5963769
23,서초구,24520928,25719896,27357211,27854157,28636972,30390265,32366952,33772132,35277030,35570338
24,강남구,46732957,49798703,51039580,53810793,57487436,62295492,63866440,65387478,69186319,71852681
25,송파구,17589054,18431887,19266071,20328884,21853310,23586997,24812660,26815980,28617470,29962528
26,강동구,6357720,6883921,7690317,7291261,7333512,7519077,7897558,8225774,8825479,9348668

In [40]:
GDP.to_csv('./data/GDP(2010-2019).csv')